"""empty message

Revision ID: 89f7e1c664bb
Revises: 7fd32d200a21
Create Date: 2024-03-18 19:23:25.671800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f7e1c664bb'
down_revision = '7fd32d200a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characterid', sa.String(length=120), nullable=False),
    sa.Column('entitytype', sa.String(length=80), nullable=False),
    sa.Column('favorite', sa.String(length=80), nullable=False),
    sa.Column('planetid', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('characterid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
