"""empty message

Revision ID: 8ab2fd38576e
Revises: 89f7e1c664bb
Create Date: 2024-03-18 19:53:51.384520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab2fd38576e'
down_revision = '89f7e1c664bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userfavorites', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['userfavorites'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userfavorites')

    # ### end Alembic commands ###
